### ISSUE TITLE
Next version of the roadmap

### ISSUE THREAD

**Issue by jmatsushita** [iilab/contentascode#33]
The roadmap is currently based on [milestones in Github](https://github.com/iilab/contentascode/milestones) and [also published on the website](http://iilab.github.io/contentascode/status/#roadmap)

But there is work needed to: 
- [x] Update the current status of issues / milestones
- [ ] Think through how to reorganise the roadmap 
- [x] Publish new version of the roadmap

**Comment by jmatsushita** [comment]
I've submitted some strategies and organised the roadmap loosely in terms of how we're achieving feature parity with some abstracted `blog` `wiki` `knowledge base`, `project management` and `cms` objectives.
