### ISSUE TITLE
Prose component

### ISSUE THREAD

**Issue by jmatsushita** [iilab/contentascode#47]
Possible aspects of Prose integration which are relevant to contentascode are:
- [ ] Integrate with Gitlab backend
- [ ] Easier "Fork and Pull Request" workflow for non techies. Including https://github.com/prose/prose/issues/643
- [ ] Other storage location for images https://github.com/iilab/contentascode/issues/5#issuecomment-183405926
- [ ] Metadata first document creation (allow to input metadata - title/date/status - **before** opening or saving a doc.  
- [ ] Transclusion support (https://github.com/iilab/prose/issues/1)
- [ ] Prosemirror integration https://github.com/iilab/contentascode/issues/5#issuecomment-197972547
- [ ] Content "Integration" tests #11 (perhaps with isomorphic tests ran by prosemirror in the client) 
- [ ] Allow offline workflow https://github.com/prose/prose/issues/690
- [ ] Persist local edits to localstorage.

@dereklieu

UPDATE: Shuffled things around and added some links.

**Comment by dereklieu** [comment]
@jmatsushita this all makes sense to me. There are a few enhancements I would consider adding, like persisting edits to localstorage when available.

Can you explain what you mean by metadata first document creation?
