### ISSUE TITLE
Define v0.1.0 goals and document Roadmap and Governance

### ISSUE THREAD

**Issue by jmatsushita** [iilab/contentascode#6]
- [ ] Discuss v0.1.0 goals
- [ ] Write v0.1.0 user stories
- [ ] First draft for overall Roadmap 
- [ ] First draft for decision making process

**Comment by jmatsushita** [comment]
There a more passive involvment from potential partners so at this stage iilab and the openintegrity project will define their own priorities for content as code, so until there's more engagement I'm closing this.
