### ISSUE TITLE
Implement Proof of concept

### ISSUE THREAD

**Issue by jmatsushita** [iilab/contentascode#7]
Needed features for a proof of concept implementation. Existing reference implementation is on this repo https://github.com/iilab/contentascode
### Authoring
- [x] Github
- [x] Jekyll
- [x] Prose
- [x] Some sort of client side validation and CI setup
### Translation
- [x] Transifex
### Collaboration
- [x] Github - Fork and pull request
- [x] Travis CI message
### Management
- [x] Waffle
### Channels
- [x] Web
- [x] Book
### CMS Parity
- [x] Comments - Github issues?
- [ ] Stats - Piwik
### Deployment
- [x] Documented installation
- [ ] Single repo and one click deploy

**Comment by jmatsushita** [comment]
Added that having Build messages properly appearing in Pull requests is also a low hanging fruit to facilitate collaboration.

**Comment by seamustuohy** [comment]
[Repositext](http://www.repositext.org/) is another implementation of a similar project that is "a collection of tools that enables a non-linear, collaborative, and distributed workflow for versioning and publishing document collections." This might be a place to look at for features to implement. The [documentation](https://github.com/imazen/repositext-guide) and actual [code](https://github.com/imazen/repositext) is also available on github. The main site also contains some possible tools that might be useful for identifying possible tools.

**Comment by jmatsushita** [comment]
Just finally looked at repositext and it does have very similar goals. There are indeed probably some good ideas to be inspired by and maybe some convergence at some later point. Thanks!
