### ISSUE TITLE
Minimum viable implementation

### ISSUE THREAD

**Issue by jmatsushita** [iilab/contentascode#8]
Needed features for a minimum viable implementation which would allow partners to adopt the workflow and technology in production.
## Authoring
- [ ] Gitlab backend
- [ ] Preview in Context
## Collaboration
- [ ] Seamless "Make a copy" and "Contribute my changes" features.
## Management
- [ ] Manage drafts
- [ ] Manage editing workflow stages
- [ ] Manage external review stages (ODT track changes?)
- [ ] 3 way diffs to maintain content variations (OS variations for tool guides)
## Reuse
- [ ] Personal media library
- [ ] Project media library
- [ ] Link management and broken link detection
## CMS Parity
- [ ] Comments
- [ ] Stats
- [ ] Search
- [ ] Recently updated - Most viewed - Recently commented on
## Flexible Structure
- [ ] Invisible Metadata Blocs in Content Authoring environment.
- [ ] Round-trip synchronisation implementation with CMSes (Drupal, Django)
## Streamlined
- [ ] Unified User Interface
