### ISSUE TITLE
Prototype implementation

### ISSUE THREAD

**Issue by jmatsushita** [iilab/contentascode#9]
Prototype should allow to do demos and showcase how key functionalities will work and improve existing content workflows.
## Authoring
- [ ] Auto date plugin for content editor
- [ ] Content category/navigation plugin for content editor
## Localisation
- [ ] Integrated Transifex Workflow
## Management
- [ ] Gitlab Kanban Leanlabs
## CMS Parity
- [ ] Comments - Isso
- [ ] Search - jekyll-search
## Interoperability
- [ ] Gollum (for github and gitlab wikis)
- [ ] Gitbook - Open Mentoring
- [ ] Android - Panic Button
## Streamlined
- [ ] Travis based deployment

**Comment by jmatsushita** [comment]
@bsenyk added Gollum as an interop goal for the platform with the aim to hookup gitlab wikis.

**Comment by jmatsushita** [comment]
Another approach to comments https://carnivalapp.io/docs

**Comment by seamustuohy** [comment]
Both [gitlabs](https://about.gitlab.com/2016/01/15/making-gitlab-better-for-large-open-source-projects/) and [github](https://github.com/blog/2111-issue-and-pull-request-templates) now support templates for pull requests and issues. Figuring out how to best integrate and utilize these will make it far easier for non-expert users to provide feedack and suggest content changes to content.

**Comment by shulter** [comment]
Idea for a TOC/md-linker from @mixmix : https://github.com/mixmix/hypermarkdown

**Comment by seamustuohy** [comment]
Also came across the interface that [common accord](http://www.commonaccord.org/) is using for [viewing, editing, and more](http://www.commonaccord.org/index.php?action=source&file=GHx/WhiteHouse/source-code-policy/pages/introduction.md) laws. It might be something to build off of of, or gain insight from for **authoring.**

**Comment by mixmix** [comment]
I'm playing with gitbook's include features at the moment.
A little fiddley but more fully featured and supported i hope.

I'm about to private it, but your can see an. Example in
github.com/hihi-2016/book

Look at the book.json and book_dev.md for examples

**Comment by mixmix** [comment]
I'm playing with gitbook's include features at the moment.
A little fiddley but more fully featured and supported i hope.

Example setup : 

book.json

``` json
{
  "gitbook": "2.x.x",
  "plugins": [ "collapsible-menu" ],
  "pluginsConfig": {
    "fontSettings": {
      "theme": "night"
    }
  },
  "variables": {
    "github": {
      "book": "https://github.com/hihi-2016/book/blob/master/"
    },
    "org": {
      "cohort": "https://github.com/hihi-2016/" 
    },
    "repo": {
      "concepts": "git+https://github.com/dev-academy-programme/curriculum.git/concepts/",
      "resources": "git+https://github.com/dev-academy-programme/curriculum.git/resources/"
    }
  },
  "styles": {
    "website": "styles/website.css"
  }
}
```

fancy_example_gitbook_include.md

``` md
{% include book.repo.concepts + 'README.md' %}
```

```
```
